---
title: "Blog"
listing:
  contents: posts
  sort: "date desc"
---

## Orientation
I found orientation really informative and fun. Except from hearing about how intense the program was, I learnt a lot about networking, future events, and what is expected from this program overall. Alongside this, the ice breakers were really fun - particularly day 2. The bonding from the strange activities we were told to do around campus definitely formed a lot of friendships. I think this was extremely well planned and helped us dive into the program smoothly. 

## First Week
The first week of classes definitely hit us hard. The workload was definitely eye opening and I'm sure it forced a lot of us to actually put our heads down and lock in. I learnt how to effectively keep track of the millions of things we have due each week by forcing myself to buy a planner for the first time in years. Although it was rough, at least we now know what to expect for the rest of the program.

## Looking ahead
Although the workload is rough, I still am looking forward to how much we will end up learning throughout this program. I am also lookign forward to my new role as the Academic Representative for Section 001, where I will get to know the students and professors more. 